name: Release Hex Cartographer Plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Generate Attestation
        uses: actions/attest-build-provenance@v1
        with:
          # Nur EINE Datei ohne Zeilenumbruch angeben
          subject-path: "main.js"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            main.js
            manifest.json
            styles.css