name: Release Hex Cartographer Plugin

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write      # Erforderlich für Attestation
      attestations: write  # Erforderlich für Attestation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: "main.js"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            main.js
            manifest.json
            styles.css